### PR TITLE
Update config files

### PR DESCRIPTION
**Pull request by deniak**
That PR syncs the config file we use in production so we can use them directly without tweaks.

### CODE REVIEW

**Review by dontcallmedom — COMMENTED** [review]
Looks good overall, but the following keys seem to be really W3C-deployment specific, and I don't think they ought to be the default configuration of the project:
```
Cache = /var/tmp/wmvs-HEAD
...
User Agent Info = https://validator.w3.org/services
...
Home Page = https://validator.w3.org/
...
HTML5 = https://validator.w3.org/nu/
CompoundXML = https://validator.w3.org/nu/
``` 
(among other things, they could create unwanted traffic on our servers)

My suspicion is that they keys would be better left as a local commit (I'm guessing there are few enough changes in this repo in general and these config files in general that the risk of a conflict preventing an auto-update should be low)

**Comment by dontcallmedom** [comment]
(I'll look into the CI failure, this clearly isn't linked to your changes)

**Comment by deniak** [comment]
> Looks good overall, but the following keys seem to be really W3C-deployment specific, and I don't think they ought to be the default configuration of the project:
> 
> ```
> Cache = /var/tmp/wmvs-HEAD
> ...
> User Agent Info = https://validator.w3.org/services
> ...
> Home Page = https://validator.w3.org/
> ...
> HTML5 = https://validator.w3.org/nu/
> CompoundXML = https://validator.w3.org/nu/
> ```
> 
> (among other things, they could create unwanted traffic on our servers)
> 
> My suspicion is that they keys would be better left as a local commit (I'm guessing there are few enough changes in this repo in general and these config files in general that the risk of a conflict preventing an auto-update should be low)

Thanks for the suggestion. I've removed/commented out these keys.
We should be able to find a way to update these in prod even if there are new commits.

**Comment by dontcallmedom** [comment]
thanks for fixing the CI!!!

**Review by dontcallmedom — APPROVED** [review]

**Pull request merged**
